New log file opened at Thu Mar 12 19:42:07 PDT 2015 by 18375@GHs-MacBook-Pro-2.local
Taking next connection to: 52011
New client attempting to connect on port: 52012-52011
  Address = /172.16.44.146:52011
This client on port 52012 has uuid 2ad33267-4c2a-42a3-8787-66510374a7f4 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-2ad33267-4c2a-42a3-8787-66510374a7f4
Taking next connection to: 52011
New client attempting to connect on port: 52013-52011
  Address = /172.16.44.146:52011
Handshake exception on socket: 52013
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 52011
New client attempting to connect on port: 52014-52011
  Address = /172.16.44.146:52011
This client on port 52014 has uuid 5e3a5574-9164-48eb-a5db-abc0cabb9dda configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-2ad33267-4c2a-42a3-8787-66510374a7f4, activator-5e3a5574-9164-48eb-a5db-abc0cabb9dda
Taking next connection to: 52011
New client attempting to connect on port: 52046-52011
  Address = /172.16.44.146:52011
Handshake exception on socket: 52046
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 52011
New client attempting to connect on port: 52047-52011
  Address = /172.16.44.146:52011
This client on port 52047 has uuid 52103722-5941-49fa-b3d1-5e4cf3939943 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-5e3a5574-9164-48eb-a5db-abc0cabb9dda, play-fork-run-52103722-5941-49fa-b3d1-5e4cf3939943
Taking next connection to: 52011
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 52011
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 52011
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 52011
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 52011
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 52011
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 52011
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 52011
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 52011
